Repository SimpleBoardTeam/simpleBoard-server, pull requests merged in 2025-07, with the labels that each got.

#17 [diagram] 이벤트 다이어그램 디렉토리 구조 변경
  document/puml/event/eventHandling/boardContext/commentAggregate/samplepuml
  document/puml/event/externalAPI/boardContext/commentAggregate/addComment.puml
  document/puml/event/externalAPI/boardContext/commentAggregate/addCommentSecq.svg
  document/puml/event/externalAPI/boardContext/postAggregate/createPost.puml
  document/puml/event/externalAPI/boardContext/postAggregate/createPostSeq.svg
  document/puml/event/internalAPI/boardContext/commentAggregate/samplepuml
Labels: documentation, refactor

#12 [Diagram] Post 이벤트 다이어그램 작성
  document/puml/event/externalAPI/boardContext/postAggregate/createPost.puml
  document/puml/event/externalAPI/boardContext/postAggregate/deletePost.puml
  document/puml/event/externalAPI/boardContext/postAggregate/deletePostSeq.svg
  document/puml/event/externalAPI/boardContext/postAggregate/getPostDetail.puml
  document/puml/event/externalAPI/boardContext/postAggregate/getPostList.puml
Labels: documentation

#19 [Infra] workflow 파일 문법 오류 수정
  .github/workflows/CI.yaml
Labels: bug

#13 [Diagram] Permission 도메인 다이어그램 작성
  document/puml/domain/boardContext.puml
  document/puml/domain/boardContext.svg
  document/puml/domain/boardcontext/boardAggregate.puml
  document/puml/domain/boardcontext/boardAggregate.svg
  document/puml/domain/boardmanagercontext/boardManagerAggregate.puml
  document/puml/domain/boardmanagercontext/boardManagerAggregate.svg
  document/puml/domain/boundedContextMap.puml
  document/puml/domain/boundedContextMap.svg
  document/puml/domain/membercontext/memberAggregate.puml
  document/puml/domain/membercontext/memberAggregate.svg
  document/puml/domain/permissioncontext/permissionPolicyAggregate.puml
  document/puml/domain/permissioncontext/permissionPolicyAggregate.svg
  document/puml/event/externalAPI/boardContext/commentAggregate/addCommentSecq.svg
  document/puml/event/externalAPI/boardContext/commentAggregate/deleteCommentSeq.svg
  document/puml/event/externalAPI/boardContext/commentAggregate/getCommentListSeq.svg
  document/puml/event/externalAPI/boardContext/postAggregate/createPostSeq.svg
  document/puml/event/externalAPI/boardContext/postAggregate/deletePostSeq.svg
  document/puml/event/externalAPI/boardContext/postAggregate/getPostDetailSeq.svg
  document/puml/event/externalAPI/boardContext/postAggregate/getPostListSeq.svg
  gradlew
Labels: documentation

#41 [infra] spring boot 버전 변경
  build.gradle
Labels: refactor

#14 [Diagram] Member 이벤트 다이어그램 작성
  document/puml/domain/boardContext.puml
  document/puml/domain/boardContext.svg
  document/puml/domain/boardcontext/permissionPolicyAggregate.puml
  document/puml/domain/boardcontext/permissionPolicyAggregate.svg
  document/puml/domain/boardcontext/userBoardRoleAggregate.svg
  document/puml/domain/boundedContextMap.puml
  document/puml/domain/boundedContextMap.svg
  document/puml/event/externalAPI/memberContext/memberAggregate/checkMemberExists.puml
  document/puml/event/externalAPI/memberContext/memberAggregate/checkMemberExists.svg
  document/puml/event/externalAPI/memberContext/memberAggregate/getMyProfile.puml
  document/puml/event/externalAPI/memberContext/memberAggregate/getMyProfile.svg
  document/puml/event/externalAPI/memberContext/memberAggregate/getProfileById.puml
  document/puml/event/externalAPI/memberContext/memberAggregate/getProfileById.svg
  document/puml/event/externalAPI/memberContext/memberAggregate/updateNickname.puml
  document/puml/event/externalAPI/memberContext/memberAggregate/updateNicknameSeq.svg
  document/puml/event/externalAPI/memberContext/memberAggregate/withdrawMember.puml
  document/puml/event/externalAPI/memberContext/memberAggregate/withdrawMember.svg
Labels: documentation

#21 [Diagram] Post 도메인 이벤트 핸들링 다이어그램 작성
  document/puml/event/eventHandling/boardContext/postAggregate/BoardDeletedHandle.puml
  document/puml/event/eventHandling/boardContext/postAggregate/BoardDeletedHandling.svg
  document/puml/event/eventHandling/boardContext/postAggregate/CommentCreatedHandle.puml
  document/puml/event/eventHandling/boardContext/postAggregate/CommentCreatedHandling.svg
  document/puml/event/eventHandling/boardContext/postAggregate/CommentDeletedHandle.puml
  document/puml/event/eventHandling/boardContext/postAggregate/CommentDeletedHandling.svg
  document/puml/event/eventHandling/boardContext/postAggregate/PostDetailQueriedHandle.puml
  document/puml/event/eventHandling/boardContext/postAggregate/PostDetailQueriedHandling.svg
  document/puml/event/externalAPI/boardContext/commentAggregate/addComment.puml
  document/puml/event/externalAPI/boardContext/commentAggregate/addCommentSecq.svg
  document/puml/event/externalAPI/boardContext/commentAggregate/deleteComment.puml
  document/puml/event/externalAPI/boardContext/commentAggregate/deleteCommentSeq.svg
  document/puml/event/externalAPI/boardContext/postAggregate/getPostDetail.puml
  document/puml/event/externalAPI/boardContext/postAggregate/getPostDetailSeq.svg
Labels: documentation, feature

#33 [Diagram] Permission 도메인 이벤트 핸들링 다이어그램 작성
  document/puml/domain/permissioncontext/PermissionPolicy_assignRole.svg
  document/puml/domain/permissioncontext/PermissionPolicy_can.svg
  document/puml/domain/permissioncontext/PermissionPolicy_delegateRole.svg
  document/puml/domain/permissioncontext/assignRole.puml
  document/puml/domain/permissioncontext/can.puml
  document/puml/domain/permissioncontext/delegateRole.puml
  document/puml/domain/permissioncontext/permissionPolicyAggregate.puml
  document/puml/domain/permissioncontext/permissionPolicyAggregate.svg
  document/puml/event/eventHandling/permissionContext/permissionAggregate/PermissionPolicy_BOARD_CREATED_HANDLE.svg
  document/puml/event/eventHandling/permissionContext/permissionAggregate/PermissionPolicy_BOARD_DELETED_HANDLE.svg
  document/puml/event/eventHandling/permissionContext/permissionAggregate/boardCreatedEventHandling.puml
  document/puml/event/eventHandling/permissionContext/permissionAggregate/boardDeletedEventHandling.puml
Labels: documentation

#32 [Diagram] Board 도메인 다이어그램 작성
  document/puml/domain/boardContext.puml
  document/puml/domain/boardContext.svg
  document/puml/domain/boardcontext/boardAggregate.puml
  document/puml/domain/boardcontext/boardAggregate.svg
  document/puml/domain/boardcontext/boardAggregate/boardAggregate.puml
  document/puml/domain/boardcontext/boardAggregate/boardAggregate.svg
  document/puml/domain/boundedContextMap.puml
  document/puml/domain/boundedContextMap.svg
Labels: documentation

#36 [Post] Post Aggregate 구현
  src/main/java/com/simpleboard/board/board/domain/common/vo/Visitor.java
  src/main/java/com/simpleboard/board/board/domain/common/vo/VisitorType.java
  src/main/java/com/simpleboard/board/board/domain/post/dto/CreateParams.java
  src/main/java/com/simpleboard/board/board/domain/post/dto/DeleteParams.java
  src/main/java/com/simpleboard/board/board/domain/post/dto/EditParams.java
  src/main/java/com/simpleboard/board/board/domain/post/dto/LikeInfo.java
  src/main/java/com/simpleboard/board/board/domain/post/entity/GuestPost.java
  src/main/java/com/simpleboard/board/board/domain/post/entity/HashTag.java
  src/main/java/com/simpleboard/board/board/domain/post/entity/MemberPost.java
  src/main/java/com/simpleboard/board/board/domain/post/entity/Post.java
  src/main/java/com/simpleboard/board/board/domain/post/entity/PostLike.java
  src/main/java/com/simpleboard/board/board/domain/post/exception/HashTagsSizeException.java
  src/main/java/com/simpleboard/board/board/domain/post/exception/MemberPostPermissionException.java
  src/main/java/com/simpleboard/board/board/domain/post/exception/PostPasswordNotMatchException.java
  src/main/java/com/simpleboard/board/board/domain/post/vo/BoardVO.java
  src/main/java/com/simpleboard/board/board/domain/post/vo/LikesVO.java
  src/main/java/com/simpleboard/board/board/domain/post/vo/PostTypeEnum.java
  src/main/java/com/simpleboard/board/board/domain/post/vo/TagsVO.java
  src/main/java/com/simpleboard/board/global/exception/ErrorCode.java
  src/main/java/com/simpleboard/board/global/exception/ServiceException.java
  src/test/java/com/simpleboard/board/board/domain/post/entity/PostCreateTest.java
  src/test/java/com/simpleboard/board/board/domain/post/entity/PostDeleteTest.java
  src/test/java/com/simpleboard/board/board/domain/post/entity/PostLikeTest.java
  src/test/java/com/simpleboard/board/board/domain/post/entity/PostPostLikeToggleTest.java
  src/test/java/com/simpleboard/board/board/domain/post/entity/PostUpdateTest.java
  src/test/java/com/simpleboard/board/board/domain/post/testutil/PostCreateParamsBuilder.java
  src/test/java/com/simpleboard/board/board/domain/post/testutil/VisitorUtil.java
  src/test/java/com/simpleboard/board/board/domain/post/vo/LikesVOTest.java
  src/test/java/com/simpleboard/board/board/domain/post/vo/TagsTest.java
Labels: feature

#46 [Global] Exception handling 로직 수정
  src/main/java/com/simpleboard/board/global/controller/BaseController.java
  src/main/java/com/simpleboard/board/global/exception/ErrorCode.java
  src/main/java/com/simpleboard/board/global/exception/ErrorResponse.java
  src/main/java/com/simpleboard/board/global/exception/GlobalExceptionHandler.java
  src/main/java/com/simpleboard/board/global/exception/ServiceException.java
Labels: refactor

#53 [Gradle] JPA 의존성 추가
  build.gradle
  src/main/java/com/simpleboard/board/global/config/JpaAuditingConfig.java
  src/main/java/com/simpleboard/board/global/entity/BaseEntity.java
  src/test/java/com/simpleboard/board/BoardApplicationTests.java
Labels: feature
