Repository SimpleBoardTeam/simpleBoard-server, pull requests merged in 2025-08, with the labels that each got.

#58 [Token] Auth - Token 도메인 서비스 개발
  src/main/java/com/simpleboard/board/auth/domain/token/dto/LoginTokenIssueCommand.java
  src/main/java/com/simpleboard/board/auth/domain/token/dto/RefreshTokenRotationCommand.java
  src/main/java/com/simpleboard/board/auth/domain/token/dto/VerifyTokenIssueCommand.java
  src/main/java/com/simpleboard/board/auth/domain/token/exception/RefreshTokenEnrollBlacklistException.java
  src/main/java/com/simpleboard/board/auth/domain/token/exception/RefreshTokenExpiredException.java
  src/main/java/com/simpleboard/board/auth/domain/token/exception/RefreshTokenInvalidException.java
  src/main/java/com/simpleboard/board/auth/domain/token/repository/MemberUUIDRepository.java
  src/main/java/com/simpleboard/board/auth/domain/token/repository/TokenBlacklistRepository.java
  src/main/java/com/simpleboard/board/auth/domain/token/service/TokenDomainService.java
  src/main/java/com/simpleboard/board/auth/domain/token/service/TokenTTLPolicy.java
  src/main/java/com/simpleboard/board/auth/domain/token/util/ClockManager.java
  src/main/java/com/simpleboard/board/auth/domain/token/util/IdGenerator.java
  src/main/java/com/simpleboard/board/auth/domain/token/util/TokenProvider.java
  src/main/java/com/simpleboard/board/auth/domain/token/vo/Role.java
  src/main/java/com/simpleboard/board/auth/domain/token/vo/Token.java
  src/main/java/com/simpleboard/board/auth/domain/token/vo/TokenClaims.java
  src/main/java/com/simpleboard/board/auth/domain/token/vo/TokenPair.java
  src/main/java/com/simpleboard/board/auth/domain/token/vo/TokenPurpose.java
  src/main/java/com/simpleboard/board/auth/domain/token/vo/VerifyPurpose.java
  src/test/java/com/simpleboard/board/auth/domain/token/service/TokenDomainServiceTest.java
  src/test/java/com/simpleboard/board/auth/domain/token/service/TokenTTLPolicyTest.java
  src/test/java/com/simpleboard/board/auth/domain/token/vo/TokenClaimsTest.java
Labels: feature

#63 [Member] Member domain 계층 구현
  src/main/java/com/simpleboard/board/global/exception/ErrorCode.java
  src/main/java/com/simpleboard/board/member/domain/BirthYear.java
  src/main/java/com/simpleboard/board/member/domain/Gender.java
  src/main/java/com/simpleboard/board/member/domain/Member.java
  src/main/java/com/simpleboard/board/member/domain/Nickname.java
  src/main/java/com/simpleboard/board/member/domain/NicknameDuplicationChecker.java
  src/main/java/com/simpleboard/board/member/domain/exception/DuplicatedNicknameException.java
  src/main/java/com/simpleboard/board/member/domain/exception/InvalidBirthYearException.java
  src/main/java/com/simpleboard/board/member/domain/repository/MemberRepository.java
  src/test/java/com/simpleboard/board/member/domain/BirthYearTest.java
  src/test/java/com/simpleboard/board/member/domain/MemberTest.java
Labels: feature

#65 [Infra] WebClient 설정 환경 구성
  build.gradle
  src/main/java/com/simpleboard/board/global/config/WebClientConfig.java
  src/main/java/com/simpleboard/board/global/exception/ErrorCode.java
  src/main/java/com/simpleboard/board/global/exception/GlobalExceptionHandler.java
  src/main/java/com/simpleboard/board/global/exception/webclient/WebClient4xxException.java
  src/main/java/com/simpleboard/board/global/exception/webclient/WebClient5xxException.java
  src/main/java/com/simpleboard/board/global/exception/webclient/WebClientErrorHandler.java
  src/test/java/com/simpleboard/board/global/exception/webclient/ErrorHandlerTestService.java
  src/test/java/com/simpleboard/board/global/exception/webclient/WebClientErrorHandlerTest.java
Labels: feature

#71 [Post] Command repository 개발
  src/main/java/com/simpleboard/board/board/infrastructure/jpa/repository/HashTagEntityRepository.java
  src/main/java/com/simpleboard/board/board/infrastructure/jpa/repository/PostCommandRepositoryImpl.java
  src/main/java/com/simpleboard/board/board/infrastructure/jpa/repository/PostEntityRepository.java
Labels: feature

#77 [Auth] Authentication Aggregate 개발
  src/main/java/com/simpleboard/board/auth/domain/auth/dto/request/RegisterParams.java
  src/main/java/com/simpleboard/board/auth/domain/auth/entity/EmailUserAuth.java
  src/main/java/com/simpleboard/board/auth/domain/auth/entity/OAuthUserAuth.java
  src/main/java/com/simpleboard/board/auth/domain/auth/entity/UserAuth.java
  src/main/java/com/simpleboard/board/auth/domain/auth/repository/AuthCommandRepository.java
  src/main/java/com/simpleboard/board/auth/domain/auth/vo/RegisterType.java
  src/main/java/com/simpleboard/board/auth/domain/auth/vo/UserState.java
Labels: feature

#84 [Global] Jasypt 적용 및 yml 파일 구조 수정
  .gitignore
  build.gradle
  src/main/java/com/simpleboard/board/global/config/JasyptConfig.java
  src/main/resources/application-common.yml
  src/main/resources/application-dev.yml
  src/main/resources/application.yaml
  src/main/resources/application.yml
Labels: feature

#81 [Auth] Token 도메인 서비스 리펙토링
  src/main/java/com/simpleboard/board/auth/domain/token/dto/request/LoginTokenIssueParam.java
  src/main/java/com/simpleboard/board/auth/domain/token/dto/request/RefreshTokenRotationParam.java
  src/main/java/com/simpleboard/board/auth/domain/token/dto/request/VerifyTokenIssueParam.java
  src/main/java/com/simpleboard/board/auth/domain/token/dto/response/LoginTokenInfo.java
  src/main/java/com/simpleboard/board/auth/domain/token/dto/response/VerifyTokenInfo.java
  src/main/java/com/simpleboard/board/auth/domain/token/exception/TokenUserBlockedException.java
  src/main/java/com/simpleboard/board/auth/domain/token/service/TokenDomainService.java
  src/main/java/com/simpleboard/board/auth/domain/token/util/TokenProvider.java
  src/main/java/com/simpleboard/board/auth/domain/token/vo/Token.java
  src/main/java/com/simpleboard/board/global/exception/ErrorCode.java
  src/test/java/com/simpleboard/board/auth/domain/token/service/TokenDomainServiceTest.java
Labels: refactor

#93 [Board] Post presentation - Command 파트 개발
  src/main/java/com/simpleboard/board/board/application/converter/PostCommandParamsConverter.java
  src/main/java/com/simpleboard/board/board/application/dto/request/PostCreateCommand.java
  src/main/java/com/simpleboard/board/board/domain/common/vo/Visitor.java
  src/main/java/com/simpleboard/board/board/domain/post/entity/Post.java
  src/main/java/com/simpleboard/board/board/domain/post/vo/BoardVO.java
  src/main/java/com/simpleboard/board/board/infrastructure/jpa/converter/PostConverter.java
  src/main/java/com/simpleboard/board/board/infrastructure/jpa/entity/embed/BoardEmbed.java
  src/main/java/com/simpleboard/board/board/presentation/converter/PostFormCommandConverter.java
  src/main/java/com/simpleboard/board/board/presentation/dto/request/PostCreateForm.java
  src/main/java/com/simpleboard/board/board/presentation/dto/request/PostDeleteForm.java
  src/main/java/com/simpleboard/board/board/presentation/dto/request/PostEditForm.java
  src/main/java/com/simpleboard/board/board/presentation/util/VisitorProvider.java
  src/main/java/com/simpleboard/board/board/presentation/web/PostCommandController.java
  src/test/java/com/simpleboard/board/board/application/service/PostCommandServiceUnitTest.java
  src/test/java/com/simpleboard/board/board/domain/post/entity/PostCreateTest.java
  src/test/java/com/simpleboard/board/board/infrastructure/jpa/converter/PostConverterUnitTest.java
Labels: feature

#102 [Board] Post 상세조회 application, infra 계층 개발
  build.gradle
  src/main/java/com/simpleboard/board/board/application/converter/PostQueryServiceRepoConverter.java
  src/main/java/com/simpleboard/board/board/application/dto/request/PostDetailsQuery.java
  src/main/java/com/simpleboard/board/board/application/dto/response/AuthorSummary.java
  src/main/java/com/simpleboard/board/board/application/dto/response/PostDetailsQueryResult.java
  src/main/java/com/simpleboard/board/board/application/query/PostDetailsCriteria.java
  src/main/java/com/simpleboard/board/board/application/query/PostDetailsReadModel.java
  src/main/java/com/simpleboard/board/board/application/query/PostQueryRepository.java
  src/main/java/com/simpleboard/board/board/application/service/MemberFetchService.java
  src/main/java/com/simpleboard/board/board/application/service/PostQueryService.java
  src/main/java/com/simpleboard/board/board/application/service/PostQueryServiceImpl.java
  src/main/java/com/simpleboard/board/board/infrastructure/mybatis/converter/PostQueryConverter.java
  src/main/java/com/simpleboard/board/board/infrastructure/mybatis/mapper/PostDetailsCondition.java
  src/main/java/com/simpleboard/board/board/infrastructure/mybatis/mapper/PostDetailsData.java
  src/main/java/com/simpleboard/board/board/infrastructure/mybatis/mapper/PostQueryMapper.java
  src/main/java/com/simpleboard/board/board/infrastructure/mybatis/repository/PostQueryRepositoryImpl.java
  src/main/resources/application-common.yml
  src/main/resources/mappers/PostQueryMapper.xml
Labels: feature

#106 [Auth] UserAuth aggregate infra 영역 개발
  src/main/java/com/simpleboard/board/auth/application/service/AuthPrincipalServiceImpl.java
  src/main/java/com/simpleboard/board/auth/domain/auth/repository/UserAuthCommandRepository.java
  src/main/java/com/simpleboard/board/auth/infrastructure/jpa/converter/AuthEntityConverter.java
  src/main/java/com/simpleboard/board/auth/infrastructure/jpa/entity/EmailUserAuthEntity.java
  src/main/java/com/simpleboard/board/auth/infrastructure/jpa/entity/OAuthUserAuthEntity.java
  src/main/java/com/simpleboard/board/auth/infrastructure/jpa/entity/UserAuthEntity.java
  src/main/java/com/simpleboard/board/auth/infrastructure/jpa/repository/UserAuthCommandRepositoryImpl.java
  src/main/java/com/simpleboard/board/auth/infrastructure/jpa/repository/UserAuthEntityRepository.java
  src/test/java/com/simpleboard/board/auth/infrastructure/jpa/converter/AuthEntityConverterTest.java
Labels: feature

#113 [Comment] infra - Command repository 구현
  src/main/java/com/simpleboard/board/board/infrastructure/jpa/converter/CommentConverter.java
  src/main/java/com/simpleboard/board/board/infrastructure/jpa/entity/CommentEntity.java
  src/main/java/com/simpleboard/board/board/infrastructure/jpa/entity/GuestCommentEntity.java
  src/main/java/com/simpleboard/board/board/infrastructure/jpa/entity/MemberCommentEntity.java
  src/main/java/com/simpleboard/board/board/infrastructure/jpa/repository/CommentCommandRepositoryImpl.java
  src/main/java/com/simpleboard/board/board/infrastructure/jpa/repository/CommentEntityRepository.java
  src/test/java/com/simpleboard/board/board/application/converter/CommentResultConverterTest.java
  src/test/java/com/simpleboard/board/board/infrastructure/jpa/converter/CommentConverterUnitTest.java
Labels: feature

#111 [Post] USECASE: 목록조회 - application, infra 계층 개발
  src/main/java/com/simpleboard/board/board/application/converter/PostQueryServiceRepoConverter.java
  src/main/java/com/simpleboard/board/board/application/dto/request/PostListQuery.java
  src/main/java/com/simpleboard/board/board/application/dto/response/PostListQueryResult.java
  src/main/java/com/simpleboard/board/board/application/exception/BoardNameNotFound.java
  src/main/java/com/simpleboard/board/board/application/query/BoardQueryRepository.java
  src/main/java/com/simpleboard/board/board/application/query/PostListCriteria.java
  src/main/java/com/simpleboard/board/board/application/query/PostListReadModel.java
  src/main/java/com/simpleboard/board/board/application/query/PostQueryRepository.java
  src/main/java/com/simpleboard/board/board/application/service/MemberFetchService.java
  src/main/java/com/simpleboard/board/board/application/service/PostQueryService.java
  src/main/java/com/simpleboard/board/board/application/service/PostQueryServiceImpl.java
  src/main/java/com/simpleboard/board/board/infrastructure/mybatis/converter/PostQueryConverter.java
  src/main/java/com/simpleboard/board/board/infrastructure/mybatis/mapper/PostListCondition.java
  src/main/java/com/simpleboard/board/board/infrastructure/mybatis/mapper/PostQueryMapper.java
  src/main/java/com/simpleboard/board/board/infrastructure/mybatis/mapper/PostSummaryData.java
  src/main/java/com/simpleboard/board/board/infrastructure/mybatis/repository/PostQueryRepositoryImpl.java
  src/main/java/com/simpleboard/board/global/exception/ErrorCode.java
  src/main/resources/mappers/PostQueryMapper.xml
Labels: feature

#116 [Auth] Auth B.C Controller 개발
  src/main/java/com/simpleboard/board/auth/application/service/TokenApplicationServiceImpl.java
  src/main/java/com/simpleboard/board/auth/application/service/UserAuthCommandServiceImpl.java
  src/main/java/com/simpleboard/board/auth/domain/auth/entity/UserAuth.java
  src/main/java/com/simpleboard/board/auth/domain/token/dto/request/VerifyTokenIssueParam.java
  src/main/java/com/simpleboard/board/auth/domain/token/service/TokenDomainService.java
  src/main/java/com/simpleboard/board/auth/presentation/dto/request/EmailRegisterForm.java
  src/main/java/com/simpleboard/board/auth/presentation/exception/EmailRegisterTokenException.java
  src/main/java/com/simpleboard/board/auth/presentation/util/AuthStringProvider.java
  src/main/java/com/simpleboard/board/auth/presentation/web/AuthenticationController.java
  src/main/java/com/simpleboard/board/auth/presentation/web/UserAuthController.java
  src/main/java/com/simpleboard/board/global/exception/ErrorCode.java
  src/test/java/com/simpleboard/board/auth/application/service/TokenApplicationServiceTest.java
  src/test/java/com/simpleboard/board/auth/application/service/UserAuthCommandServiceTest.java
  src/test/java/com/simpleboard/board/auth/domain/token/service/TokenDomainServiceTest.java
Labels: feature

#118 [Comment] Command controller 개발
  src/main/java/com/simpleboard/board/board/presentation/converter/CommentFormCommandConverter.java
  src/main/java/com/simpleboard/board/board/presentation/converter/CommentResultResponseConverter.java
  src/main/java/com/simpleboard/board/board/presentation/dto/request/CommentCreateForm.java
  src/main/java/com/simpleboard/board/board/presentation/dto/request/CommentDeleteForm.java
  src/main/java/com/simpleboard/board/board/presentation/dto/response/CommentDetailResponse.java
  src/main/java/com/simpleboard/board/board/presentation/web/CommentCommandController.java
  src/test/java/com/simpleboard/board/board/presentation/converter/CommentFormCommandConverterTest.java
  src/test/java/com/simpleboard/board/board/presentation/converter/CommentResultResponseConverterTest.java
Labels: feature

#119 [Comment] CommandRepository 테스트 추가
  src/test/java/com/simpleboard/board/board/domain/comment/repository/CommentCommandRepositoryTest.java
Labels: feature

#121 [Infra] CI workflow에 Spotless check 추가
  .github/workflows/CI.yaml
  src/main/java/com/simpleboard/board/auth/application/exception/NicknameConflictException.java
  src/main/java/com/simpleboard/board/auth/application/service/TokenApplicationServiceImpl.java
  src/main/java/com/simpleboard/board/auth/application/service/VerificationCommandService.java
  src/main/java/com/simpleboard/board/auth/domain/auth/dto/request/RegisterParams.java
  src/main/java/com/simpleboard/board/auth/domain/token/dto/request/VerifyTokenIssueParam.java
  src/main/java/com/simpleboard/board/auth/domain/token/service/TokenDomainService.java
  src/main/java/com/simpleboard/board/auth/infrastructure/jwt/JwtTokenProvider.java
  src/main/java/com/simpleboard/board/auth/presentation/util/AuthStringProvider.java
  src/main/java/com/simpleboard/board/board/application/service/CommentCommandServiceImpl.java
  src/main/java/com/simpleboard/board/board/domain/board/entity/Board.java
  src/main/java/com/simpleboard/board/board/infrastructure/jpa/converter/CommentConverter.java
  src/main/java/com/simpleboard/board/board/infrastructure/jpa/entity/CommentEntity.java
  src/main/java/com/simpleboard/board/board/infrastructure/jpa/entity/GuestCommentEntity.java
  src/main/java/com/simpleboard/board/board/infrastructure/jpa/entity/MemberCommentEntity.java
  src/main/java/com/simpleboard/board/board/infrastructure/jpa/repository/CommentCommandRepositoryImpl.java
  src/main/java/com/simpleboard/board/board/infrastructure/jpa/repository/CommentEntityRepository.java
  src/main/java/com/simpleboard/board/board/infrastructure/mybatis/mapper/PostDetailsCondition.java
  src/main/java/com/simpleboard/board/board/infrastructure/mybatis/mapper/PostDetailsData.java
  src/main/java/com/simpleboard/board/board/infrastructure/mybatis/mapper/PostSummaryData.java
  src/main/java/com/simpleboard/board/board/presentation/dto/request/CommentCreateForm.java
  src/main/java/com/simpleboard/board/board/presentation/dto/request/CommentDeleteForm.java
  src/main/java/com/simpleboard/board/board/presentation/dto/response/CommentDetailResponse.java
  src/main/java/com/simpleboard/board/global/exception/ErrorCode.java
  src/main/java/com/simpleboard/board/permission/infrastructure/mapper/ManagerAssignmentMapper.java
  src/main/java/com/simpleboard/board/permission/infrastructure/mapper/PermissionPolicyMapper.java
  src/main/java/com/simpleboard/board/permission/infrastructure/repository/InMemoryRoleCatalog.java
  src/main/java/com/simpleboard/board/permission/presentation/PermissionController.java
  src/main/java/com/simpleboard/board/permission/presentation/PermissionEventHandler.java
  src/main/java/com/simpleboard/board/permission/presentation/PermissionEventHandlerImpl.java
  src/main/java/com/simpleboard/board/permission/presentation/PermissionFakeController.java
  src/main/java/com/simpleboard/board/permission/presentation/PermissionInternalController.java
  src/main/java/com/simpleboard/board/permission/presentation/converter/DelegateRoleConverter.java
  src/main/java/com/simpleboard/board/permission/presentation/tmp/BoardCreatedEvent.java
  src/main/java/com/simpleboard/board/permission/presentation/tmp/BoardDeletedEvent.java
  src/test/java/com/simpleboard/board/auth/application/service/TokenApplicationServiceTest.java
  src/test/java/com/simpleboard/board/auth/application/service/UserAuthCommandServiceTest.java
  src/test/java/com/simpleboard/board/auth/infrastructure/jwt/JwtTokenProviderTest.java
  src/test/java/com/simpleboard/board/board/application/service/CommentCommandServiceTest.java
  src/test/java/com/simpleboard/board/board/domain/comment/repository/CommentCommandRepositoryTest.java
  src/test/java/com/simpleboard/board/board/infrastructure/jpa/converter/CommentConverterUnitTest.java
  src/test/java/com/simpleboard/board/board/presentation/converter/CommentFormCommandConverterTest.java
  src/test/java/com/simpleboard/board/board/presentation/converter/CommentResultResponseConverterTest.java
  src/test/java/com/simpleboard/board/permission/presentation/PermissionEventHandlerImplTest.java
  src/test/java/com/simpleboard/board/permission/presentation/PermissionInternalControllerTest.java
  src/test/java/com/simpleboard/board/testconfig/JpaAuditTestConfig.java
Labels: enhancement
